#mysql datasource 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dasboot?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #Connection pooling properties
    tomcat:
      max-active: 10
      max-idle: 8
      max-wait: 10000
      min-evictable-idle-time-millis: 1000
      min-idle: 8
      time-between-eviction-runs-millis: 1
    dbcp2:
      test-while-idle: true
      validation-query: select 1
         
 #jpa properties     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  #flyway:
    #baseline-on-migrate: true
    #url: jdbc:mysql://localhost:3306/dasboot?useSSL=false
    #user: root
    #password: root 
    
    
